# -*- mode: ruby -*-
# vi: set ft=ruby :

# Change on demand
APPLY_SECRET_CONFIG = false
SSH_USERNAME = 'ubuntu'
CONFIG_NAME = 'vagrant-os-production'

require_relative '../Vagrantfile_base'

# Is this needed?
require 'vagrant-openstack-plugin'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # VM
  config.vm.hostname = 'cwb-server-openstack'

  # Box
  config.vm.box     = 'openstack'
  config.vm.box_url = 'https://github.com/cloudbau/vagrant-openstack-plugin/raw/master/dummy.box'

  # Make sure the private key from the key pair is provided
  config.ssh.private_key_path = '/Users/philipp/Documents/Openstack/philipp.pem'

  # Openstack provider
  config.vm.provider :openstack do |os|
    os.username     = ENV['OS_USERNAME'].to_s
    os.api_key      = ENV['OS_PASSWORD'].to_s
    os.flavor       = /m1.small/    # Regex or String
    os.image        = /Ubuntu.*13/  # Regex or String
    os.endpoint     = 'http://openstack.infosys.tuwien.ac.at:5000/v2.0/tokens'  # e.g. "#{ENV['OS_AUTH_URL']}/tokens"
    os.keypair_name = 'philipp'      # as stored in Nova
    os.ssh_username = SSH_USERNAME
    os.server_name  = 'Cloud-Workbench'
    os.floating_ip  = '128.130.172.195'
  end

  # Chef solo
  config.vm.provision :chef_solo, id: 'chef_solo' do |chef|
    chef.add_recipe 'build-essential'
    chef.json = CHEF_JSON.deep_merge(
    {
      'cloud-benchmarking-server' => {
          'delayed_job' => {
              'worker_processes' => '8'
          },
      },
    }
    )
  end
end
