source "https://api.berkshelf.com"

metadata

# Improved version of the fork https://github.com/melonhead-cookbooks/vagrant-cookbook
#cookbook 'vagrant', path: '../vagrant'
# Alternatively use the version from bitbucket
# cookbook 'vagrant', git: 'git@bitbucket.org:sealuzh/cloud-benchmarking.git',
# 				    protocol: :ssh,
# 				    rel: 'chef-repo/site-cookbooks/vagrant'


# Include all local site-cookbooks except this cookbook itself (avoid reflexive dependency).
# Note that the directory name MUST match the cookbook name
require 'pathname'
pn = Pathname.new(File.expand_path(__FILE__))
own_dir_name = pn.parent.basename.to_s
Dir.glob('../../site-cookbooks/*').each do |path|
  dir_name = File.basename(path).to_s
  if (File.directory? path) && (dir_name != own_dir_name)
    cookbook(dir_name, path: path)
  end
end
