Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # AWS EC2 provider
  config.vm.provider :aws do |aws, override|
    aws.region = "eu-west-1"
    # Official Ubuntu 14.04 LTS image for eu-west-1 from Canonical:
    #  https://cloud-images.ubuntu.com/locator/ec2/
    aws.ami = "ami-896c96fe"
    override.ssh.username = "ubuntu"
    aws.instance_type = "t1.micro"
  end

  config.vm.provision "chef_client", id: "chef_client" do |chef|
    chef.add_recipe "sysbench"
    chef.json =
        {
            "sysbench" => {
                "cli_options" => {
                    "test" => "cpu",
                    "repetitions" => "2",
                    "cpu-max-prime" => "10000",
                }
            }
        } # END json
  end
end
