# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'pathname'
# Only for debugging via binding.pry. See: http://pryrepl.org/
#require 'pry'

# Determine whether secret configuration including SSH keys should be updated.
APPLY_SECRET_CONFIG = true

# Username used to ssh into VM instances. Might be 'root' for debian images.
SSH_USERNAME = 'ubuntu'

# Local paths
FILE_DIR = Pathname.new(__FILE__).parent.expand_path
REPO_ROOT = FILE_DIR.parent.parent.expand_path
CONFIG_DIR = FILE_DIR
SITE_COOKBOOKS = "#{REPO_ROOT}/chef-repo/site-cookbooks"
CWB_CHEF_SERVER_ROOT = "#{SITE_COOKBOOKS}/cbench-chef-server"
CWB_SERVER_ROOT = "#{SITE_COOKBOOKS}/cloud-benchmarking-server"

# CWB-Server Default configuration
require_relative "#{CWB_SERVER_ROOT}/vagrant/cwb_config"
require_relative "#{CWB_SERVER_ROOT}/vagrant/hash"
cwb_config = CwbConfig.new(config_dir: CONFIG_DIR,
                           apply_secrets: APPLY_SECRET_CONFIG,
                           ssh_username: SSH_USERNAME)
CHEF_JSON = cwb_config.chef_config


VAGRANTFILE_API_VERSION = '2'
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Detects vagrant-omnibus plugin
  if Vagrant.has_plugin?('vagrant-omnibus')
    config.omnibus.chef_version = :latest
  else
    puts "FATAL: Vagrant-omnibus plugin not detected. Please install the plugin with\n
                 'vagrant plugin install vagrant-omnibus' from any other directory\n
                 before continuing."
    exit
  end

  # Box
  config.vm.box     = 'openstack'
  config.vm.box_url = 'https://github.com/cloudbau/vagrant-openstack-plugin/raw/master/dummy.box'

  # Openstack SSH
  config.ssh.private_key_path = 'path/to/your/openstack_ssh_key.pem'

  # Openstack default configuration (applies to both VMs)
  config.vm.provider :openstack do |os|
    os.username     = 'your_openstack_username'
    os.api_key      = 'your_openstack_api_key'
    os.flavor       = /m1.small/    # Regex or String
    os.image        = /Ubuntu.*13/  # Regex or String
    os.endpoint     = 'http://openstack.yourdomain.com:5000/v2.0/tokens'  # e.g. "#{ENV['OS_AUTH_URL']}/tokens"
    os.keypair_name = 'openstack_ssh_key_name'      # as stored in Nova
    os.ssh_username = SSH_USERNAME
  end

  ### Chef-Server
  config.vm.define 'chef_server' do |chef_server|
    # VM
    chef_server.vm.hostname = 'chef-server' # MUST not contain spaces

    # Openstack
    chef_server.vm.provider :openstack do |os|
      os.server_name  = 'Chef-Server'
      os.floating_ip  = 'A.B.C.D'
    end

    # Chef solo provisioning via Berkshelf-vendored cookbooks
    chef_server.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = "#{CWB_CHEF_SERVER_ROOT}/berks-cookbooks"
      chef.add_recipe 'cbench-chef-server'
      chef.json = {
          'chef-server' => {
              # Current version as of 2014-07-16
              # See: http://www.getchef.com/chef/install/
              'version' => '11.1.6' # or 'latest'
              # Provide if cookbook service is not working correct. Autodetection tried via Ohai (see attributes)
              # 'api_fqdn' => "ec2-54-216-50-158.eu-west-1.compute.amazonaws.com"
          }
      }
    end
  end

  ### CWB-Server
  config.vm.define 'cwb_server', primary: true do |cwb_server|
    # VM
    cwb_server.vm.hostname = 'cwb-server' # MUST not contain spaces

    # Openstack
    cwb_server.vm.provider :openstack do |os|
      os.server_name  = 'Cloud-Workbench'
      os.floating_ip  = 'A.B.C.D'
    end

    # Chef solo provisioning via berks-vendored cookbooks
    cwb_server.vm.provision :chef_solo, id: 'chef_solo' do |chef|
      chef.cookbooks_path = "#{CWB_SERVER_ROOT}/berks-cookbooks"
      chef.provisioning_path = '/etc/chef'
      chef.add_recipe 'cloud-benchmarking-server'
      chef.json = CHEF_JSON.deep_merge(
      {
          'cloud-benchmarking-server' => {
              'delayed_job' => {
                  # Determines how many benchmarks can be prepared, started, or released in parallel.
                  # Keep in mind that workers are memory-intensive since the currently load the entire Rails environment.
                  'worker_processes' => '2'
              },
          },
      }
      )
    end
  end
end
