# -*- mode: ruby -*-
# vi: set ft=ruby :

# Change on demand
APPLY_SECRET_CONFIG = false
SSH_USERNAME = 'ubuntu'
CONFIG_NAME = 'vagrant-aws-retired'

require_relative '../Vagrantfile_aws'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # AWS
  config.vm.provider :aws do |aws, override|
    aws.tags = {
        'Name' => 'CWB-Server-Retired'
    }
  end

  # Chef solo
  config.vm.provision :chef_solo, id: 'chef_solo' do |chef|
    chef.json = CHEF_JSON.deep_merge(
    {
      'cloud-benchmarking-server' => {
          'delayed_job' => {
              'worker_processes' => '4'
          },
      },
      # Optimize memory for t1.small(~500mb) instance
      'rackbox' => {
          'default_config' => {
              'unicorn' => {
                  'worker_processes' => '2',
              }
          }
      },
      'postgresql' => {
          'config' => {
              'max_connections' => '20'
          },
      }
    }
    )
  end
end
