# -*- mode: ruby -*-
# vi: set ft=ruby :

SSH_USERNAME = "ubuntu"

Vagrant.configure('2') do |config|
  # Detects vagrant-omnibus plugin
  if Vagrant.has_plugin?('vagrant-omnibus')
    config.omnibus.chef_version = :latest
  else
    puts "FATAL: Vagrant-omnibus plugin not detected. Please install the plugin with\n
                 'vagrant plugin install vagrant-omnibus' from any other directory\n
                 before continuing."
    exit
  end
  
  # Detects vagrant-berkshelf plugin
  if Vagrant.has_plugin?('berkshelf')
    config.berkshelf.enabled = true
    config.berkshelf.berksfile_path = '../Berksfile'
  else
    puts "FATAL: Vagrant-berkshelf plugin not detected. Please install the plugin with\n
                 'vagrant plugin install vagrant-berkshelf' from any other directory\n
                 before continuing."
    exit
  end


  # Box
  config.vm.box = 'aws-box'
  config.vm.box_url = 'https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box'

  # VM
  config.vm.hostname = 'work-bench-aws-staging'
  config.ssh.forward_agent = true

  # AWS EC2 provider
  config.vm.provider :aws do |aws, override|
    # AWS authentication
    aws.access_key_id = ENV['AWS_ACCESS_KEY']
    aws.secret_access_key = ENV['AWS_SECRET_KEY']
    
    # AWS instance configuration
    aws.region = "eu-west-1"
    aws.region_config "eu-west-1" do |region|
      # Preinstalled instance of CloudBenchmark-Server-Production (WorkBench)
      # Note: Irritating AMI name (copied wrong name by mistake!)
      # AMI name: CloudBenchmarking-ChefServer-Production_configured_v2
      region.ami = "ami-6165a116"
      
      # Use this image if you want to install an instance from scratch
      # Official Ubuntu 12.04 image from Canonical: https://cloud-images.ubuntu.com/locator/ec2/
      # region.ami = "ami-51e91b26"
      region.keypair_name = ENV['EC2_KEYPAIR']
    end
    override.ssh.private_key_path = ENV['EC2_PRIVATE_KEY']
    override.ssh.username = SSH_USERNAME
    aws.instance_type = "t1.micro"
    aws.security_groups = ["aic13-cloud_benchmarking-web"]
    # Creation fails if no more elastic ips are available and
    # the instance is immediately shutdown!
    # aws.elastic_ip = true # Always creates a new elastic ip
    aws.tags = {
      'Name' => 'CloudBenchmarking-Server-Staging'
     }
  end

  # Chef solo provisioning via vagrant-berkshelf plugin
  config.vm.provision :chef_solo do |chef|
    # chef.cookbooks_path = "../berks-cookbooks"
    chef.run_list = [
      'recipe[cloud-benchmarking-server]'
    ]
    chef.json = {
      # For a list of time zones see: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      "tz" => "Europe/Zurich",
      "appbox" => {
        "deploy_keys" => [
          "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaea+LWlsLHA+NaIHDAETymdFToH9FcTvxDGHydE8bxAvlebXq625wF9/YX8qVN6ahcFME32JbNfFSYlp8KGDCa+qNazVawdhsOrEqsudOgZRuizlTI8AjEbbNvVyanQ+c5F/+zLW0v+/N+gk203k7v9lptYlmUQEmLg5EDEwpSrVAVmyfwZr5sMtSa6Ll3WFydGwTxmtGSfzTehMcRHCN/gyk5EOcJScP0PHq6RNSwN6ZPClXuOWBL+2wJ62yNUDm5fPM/X8RgB2IBczO0h7+j51zT85HiE99o5ILfMQjZ/yff6t+qJwJS+DXVZrGs2X3CM3pSxcONKYr9AlTfn+P joel-key-pair-ireland",
          "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCD+BQ5ILiCrn4IIoabtQOz7iAhQV48LfqdSlrxTMIoDrAzKZdyfGlhaRydLz7acdfd/PJG8IzaskinGdQYM3NfkPFniyU72ir07/QykQDbgadEA5XP4o1Tm0hUPs1Wt7OHBWzYxYjhYJN7Rnun7Pc/Xj4D7Dr48FJQUxUvAPLYJQ== joel.scheuner.dev@gmail.com"
          ],
        "admin_keys" => [
          "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaea+LWlsLHA+NaIHDAETymdFToH9FcTvxDGHydE8bxAvlebXq625wF9/YX8qVN6ahcFME32JbNfFSYlp8KGDCa+qNazVawdhsOrEqsudOgZRuizlTI8AjEbbNvVyanQ+c5F/+zLW0v+/N+gk203k7v9lptYlmUQEmLg5EDEwpSrVAVmyfwZr5sMtSa6Ll3WFydGwTxmtGSfzTehMcRHCN/gyk5EOcJScP0PHq6RNSwN6ZPClXuOWBL+2wJ62yNUDm5fPM/X8RgB2IBczO0h7+j51zT85HiE99o5ILfMQjZ/yff6t+qJwJS+DXVZrGs2X3CM3pSxcONKYr9AlTfn+P joel-key-pair-ireland"
          ]
      },
      "cbench-rackbox" => {
        "add_group_sudoers" => [ SSH_USERNAME ]
      },
      # Optimize memory for t1.small(~500mb) instance
      "rackbox" => {
        "default_config" => {
          "unicorn" => {
            "worker_processes" => "2"
          }
        }
      },
      "postgresql" => {
        "config" => {
          "max_connections" => "10"
        },
        "config_pgtune" => {
          "db_type" => "desktop"
        }
      },
      "databox" => {
        "db_root_password" => "cloud-ba-Ri-Uv",
        "databases" => {
          "postgresql" => [
            { "username" => "cloud",
              "password" => "uc-Au",
              "database_name" => "cloud_benchmarking_production" }
          ]
        }
      }
    }
  end
end
