# -*- mode: ruby -*-
# vi: set ft=ruby :

# Change on demand
APPLY_SECRET_CONFIG = false
SSH_USERNAME = 'root'
CONFIG_NAME = 'vagrant-gce-production'

require_relative '../Vagrantfile_base'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # VM
  config.vm.hostname = 'cwb-server-google'

  # Box
  config.vm.box = 'google'
  config.vm.box_url = 'https://github.com/mitchellh/vagrant-google/raw/master/google.box'

  # Google provider
  config.vm.provider :google do |google, override|
    google.google_project_id = 'lucid-honor-419' # better use: ENV['GOOGLE_PROJECT_ID']
    google.google_client_email = '410582981346@developer.gserviceaccount.com' # better use: ENV['GOOGLE_CLIENT_EMAIL']
    google.google_key_location = 'TODO' # better use: ENV['GOOGLE_KEY_LOCATION']
    google.image = 'debian-7-wheezy-v20140619'
    google.machine_type = 'n1-standard-1'
    google.name = 'CWB-Server-Production'

    override.ssh.username = SSH_USERNAME
    override.ssh.private_key_path = '~/.ssh/id_rsa'
  end

  # Chef solo
  config.vm.provision :chef_solo, id: 'chef_solo' do |chef|
    chef.add_recipe 'build-essential'
    chef.json = CHEF_JSON.deep_merge(
    {
       'build-essential' => {
           'compile_time' => true
       },
       'cloud-benchmarking-server' => {
           'delayed_job' => {
               'worker_processes' => '8'
           },
       },
    }
    )
  end
end
