require 'pathname'


source "https://api.berkshelf.com"

metadata

def cookbooks_dir
  pn = Pathname.new(File.expand_path(__FILE__))
  cwb_server = pn.parent
  cwb_server.parent.to_s
end

def local_cookbook(name)
  cookbook name, path: File.join(cookbooks_dir, name)
end

local_cookbook 'cbench-databox'
local_cookbook 'cbench-nodejs'
local_cookbook 'cbench-rackbox'
local_cookbook 'vagrant'
