Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider :aws do |aws|
    aws.region = "eu-west-1" # Ireland
    aws.ami = "ami-896c96fe" # Ubuntu 14.04 LTS image
    aws.instance_type = "t1.micro"
  end

  config.vm.provision "chef_client", id: "chef_client" do |chef|
    chef.add_recipe "recipe[demo-bench]"
    chef.json =
    {
      "demo-bench" => {
        "cpu_max_prime" => "10000"
      }
    } # END json
  end
end
