# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  # Plugin-specific configurations
  # Detects vagrant-cachier plugin
  if Vagrant.has_plugin?('vagrant-cachier')
    puts 'INFO:  Vagrant-cachier plugin detected. Optimizing caches.'
    config.cache.auto_detect = true
    config.cache.enable :chef
    config.cache.enable :apt
  else
    puts 'WARN:  Vagrant-cachier plugin not detected. Continuing unoptimized.'
  end

  # Detects vagrant-omnibus plugin
  if Vagrant.has_plugin?('vagrant-omnibus')
    puts 'INFO:  Vagrant-omnibus plugin detected.'
    config.omnibus.chef_version = :latest
  else
    puts "FATAL: Vagrant-omnibus plugin not detected. Please install the plugin with\n       'vagrant plugin install vagrant-omnibus' from any other directory\n       before continuing."
    exit
  end

  # Box
  config.vm.box = 'opscode-ubuntu-12.04'
  config.vm.box_url = 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box'
  
  # VM
  config.vm.hostname = 'chef-server-virtualbox-development'
  config.ssh.forward_agent = true
  #config.ssh.pty = true

  # VirtualBox
  config.vm.network :private_network, :ip => '33.33.33.50'

  config.vm.provider :virtualbox do |vb|
    # Give enough horsepower to build without taking all day.
    vb.customize [
      'modifyvm', :id,
      '--memory', '2024',
      '--cpus', '2',
    ]
  end

  # Chef solo provisioning via berkshelf vendored cookbooks
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../../../berks-cookbooks"
    chef.run_list = [
      'recipe[cbench-chef-server]'
    ]
    chef.json = {
      'chef-server' => {
        'version' => :latest
        # Required in order to work properly! Try autodetection in wrapper cbench wrapper cookbook
        # 'api_fqdn' => "ec2-54-216-50-158.eu-west-1.compute.amazonaws.com"
      }
    }
  end
end
