# -*- mode: ruby -*-
# vi: set ft=ruby :

# Change on demand
APPLY_SECRET_CONFIG = false
SSH_USERNAME = 'ubuntu'
CONFIG_NAME = 'vagrant-aws-production'

require_relative '../Vagrantfile_aws'

Vagrant.configure('2') do |config|
  # AWS
  config.vm.provider :aws do |aws, override|
    # Use snapshot image from production instance.
    aws.ami = 'ami-055b9172'
    aws.instance_type = 'm3.large'
    aws.tags = {
        'Name' => 'CWB-Server-Production'
    }
  end

  config.vm.provision :chef_solo, id: 'chef_solo' do |chef|
    chef.json = CHEF_JSON.deep_merge(
    {
      'cloud-benchmarking-server' => {
          'delayed_job' => {
              'worker_processes' => '12'
          },
      },
    }
    )
  end
end
