# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Detects vagrant-omnibus plugin
  if Vagrant.has_plugin?('vagrant-omnibus')
    config.omnibus.chef_version = :latest
  else
    puts "FATAL: Vagrant-omnibus plugin not detected. Please install the plugin with\n
                 'vagrant plugin install vagrant-omnibus' from any other directory\n
                 before continuing."
    exit
  end

  # Box
  config.vm.box = 'aws'
  config.vm.box_url = 'https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box'

  # VM
  config.vm.hostname = 'chef-server-staging'
  config.ssh.forward_agent = true

  # AWS
  config.vm.provider :aws do |aws, override|
    # Authentication
    aws.access_key_id = ENV['AWS_ACCESS_KEY'].to_s
    aws.secret_access_key = ENV['AWS_SECRET_KEY'].to_s

    # Instance configuration
    aws.region = 'eu-west-1'
    # Official Ubuntu 12.04 image from Canonical: https://cloud-images.ubuntu.com/locator/ec2/
    aws.ami = 'ami-51e91b26'
    aws.keypair_name = ENV['EC2_KEYPAIR'].to_s
    override.ssh.private_key_path = ENV['EC2_PRIVATE_KEY'].to_s
    override.ssh.username = 'ubuntu'
    # NOTE: t1.micro cannot satisfy the memory requirements of the chef-server
    aws.instance_type = 'm1.small'
    aws.security_groups = ['aic13-cloud_benchmarking-web']
    # aws.elastic_ip = true # Always creates a new elastic ip
    aws.tags = {
      'Name' => 'CWB-ChefServer-Staging'
    }
  end

  # Chef solo provisioning via Berkshelf-vendored cookbooks
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = '../../../berks-cookbooks'
    chef.run_list = [
        'recipe[cbench-chef-server]'
    ]
    chef.json = {
      'chef-server' => {
          'version' => :latest
          # Provide if cookbook service is not working correct. Autodetection tried via Ohai (see attributes)
          # 'api_fqdn' => "ec2-54-216-50-158.eu-west-1.compute.amazonaws.com"
      }
    }
  end
end
