# -*- mode: ruby -*-
# vi: set ft=ruby :

# Change on demand
APPLY_SECRET_CONFIG = false
SSH_USERNAME = 'vagrant'
CONFIG_NAME = 'vagrant-virtualbox-development'
# PRIVATE_IP = '33.33.33.10'

require_relative '../Vagrantfile_virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use the following configuration options on demand.

  # Enable if you want to use an attached terminal
  # config.ssh.pty = true

  # Virtualbox
  # config.vm.provider :virtualbox do |vb|
  #   vb.memory = 3000
  #   vb.cpus = 4
  # end

  # # Chef solo
  # config.vm.provision :chef_solo, id: 'chef_solo' do |chef|
  #   chef.json = CHEF_JSON.deep_merge(
  #   {
  #     'cloud-benchmarking-server' => {
  #         'delayed_job' => {
  #             'worker_processes' => '2'
  #         },
  #     },
  #     'rackbox' => {
  #         'default_config' => {
  #             'unicorn' => {
  #                 'worker_processes' => '2',
  #             }
  #         }
  #     },
  #     'postgresql' => {
  #         'config' => {
  #             'max_connections' => '20'
  #         },
  #     }
  #   }
  #   )
  # end
end
